name: ci-for-client-server
on: workflow_dispatch
jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: navigate-to-backend
        working-directory: ./backend
        run: npm ci
      - name: install-dependencies
        run: npm install
      - name: lint
        run: npm run lint
  lint-fronend:
    needs: lint-backend
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: navigate-to-frontend
        working-directory: ./client
        run: cd client
      - name: install-dependencies
        run: npm install
      - name: lint
        run: npm run lint
